"""
agents/kg_agent.py
Execute the SPARQL query generated by sparql_agent against GraphDB.
"""
from graphdb.graphdb_client import run_query


def kg_agent(state: dict) -> dict:
    sparql_query = state.get("sparql_query", "")
    if not sparql_query:
        state["error"] = "No SPARQL query found in state."
        return state

    result = run_query(sparql_query)

    if "error" in result:
        state["error"] = result["error"]
    else:
        state["kg_result"] = result

    return state